export interface DocPage {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  categoryId: string;
  author: string;
  status: "PUBLISHED";
  version: string;
  updatedAt: string;
}

export interface DocCategory {
  id: string;
  title: string;
  description: string;
  icon?: string;
  slug: string;
}

export const docCategories: DocCategory[] = [
  { id: "cat-getting-started", title: "Getting Started", description: "Set up your account and make your first generation", icon: "Rocket", slug: "getting-started" },
  { id: "cat-image-generation", title: "Image Generation", description: "Master image creation with Intellix", icon: "Image", slug: "image-generation" },
  { id: "cat-api-reference", title: "API Reference", description: "Integrate generation into your apps", icon: "Code", slug: "api-reference" },
  { id: "cat-guides", title: "Guides", description: "Tips and best practices", icon: "BookOpen", slug: "guides" },
];

export const docPages: DocPage[] = [
  {
    id: "doc-quick-start",
    slug: "quick-start",
    title: "Quick Start",
    excerpt: "Create your first AI generation in 5 minutes.",
    categoryId: "cat-getting-started",
    author: "Intellix Team",
    status: "PUBLISHED",
    version: "1.0",
    updatedAt: "2026-01-15T00:00:00.000Z",
    content: [
      "# Quick Start",
      "",
      "Welcome to Intellix! This guide walks you through creating your first AI image in under five minutes.",
      "",
      "## 1. Create an account",
      "",
      "Sign up at the login page with your email and a password. Your free plan includes a daily quota of generations.",
      "",
      "## 2. Write a prompt",
      "",
      "Open the **Generate** page from the sidebar and describe what you want to see. For example:",
      "",
      "> A cinematic portrait of a robot gardener tending a neon greenhouse, moody lighting",
      "",
      "## 3. Choose a model and settings",
      "",
      "- **Flux Dev** - higher quality, recommended default",
      "- **Flux Schnell** - faster generation",
      "",
      "You can adjust the aspect ratio and the number of images (up to 4).",
      "",
      "## 4. Generate",
      "",
      "Click **Generate** and wait a few seconds. Your images appear in the preview panel and are saved to your history.",
      "",
      "## 5. Next steps",
      "",
      "- Save prompts you like for reuse",
      "- Organize work into projects",
      "- Check your remaining quota in the sidebar",
    ].join("\n"),
  },
  {
    id: "doc-image-overview",
    slug: "image-generation/overview",
    title: "Image Generation Overview",
    excerpt: "How generation works, models, and parameters.",
    categoryId: "cat-image-generation",
    author: "Intellix Team",
    status: "PUBLISHED",
    version: "1.0",
    updatedAt: "2026-01-15T00:00:00.000Z",
    content: [
      "# Image Generation Overview",
      "",
      "Intellix generates images from text prompts using open models served by our provider network.",
      "",
      "## Models",
      "",
      "- **Flux Dev** - balanced quality and speed. Great default.",
      "- **Flux Schnell** - the fast tier, best for quick drafts.",
      "",
      "## Parameters",
      "",
      "| Parameter | Description |",
      "| --- | --- |",
      "| Prompt | The text describing the image |",
      "| Negative prompt | Things to avoid in the result |",
      "| Aspect ratio | 1:1, 4:3, 3:4, 16:9, 9:16, 21:9 |",
      "| Image count | 1 to 4 images per generation |",
      "| Resolution | High, medium or low quality tier |",
      "",
      "## Quota",
      "",
      "Each generation consumes credits from your daily quota. Check `usage/me` to see how many you have left.",
    ].join("\n"),
  },
  {
    id: "doc-api-generation",
    slug: "api-reference/generation",
    title: "API Reference: Generation",
    excerpt: "Generate images programmatically via the API.",
    categoryId: "cat-api-reference",
    author: "Intellix Team",
    status: "PUBLISHED",
    version: "1.0",
    updatedAt: "2026-01-15T00:00:00.000Z",
    content: [
      "# Generation API",
      "",
      "All requests require a `Bearer` token obtained from `POST /v1/auth/login`.",
      "",
      "## Create a generation",
      "",
      "```json",
      "POST /v1/generate",
      "Authorization: Bearer <token>",
      "",
      "{",
      "  \"prompt\": \"a fox in a spacesuit\",",
      "  \"negativePrompt\": \"blurry\",",
      "  \"imageCount\": 2,",
      "  \"ratio\": \"1:1\",",
      "  \"resolution\": \"high\",",
      "  \"model\": \"flux\"",
      "}",
      "```",
      "",
      "## List history",
      "",
      "```text",
      "GET /v1/generation/history?limit=20&offset=0",
      "```",
      "",
      "## Delete a generation",
      "",
      "```text",
      "DELETE /v1/generation/history/:id",
      "```",
    ].join("\n"),
  },
  {
    id: "doc-prompt-engineering",
    slug: "guides/prompt-engineering",
    title: "Prompt Engineering",
    excerpt: "Write better prompts for stunning results.",
    categoryId: "cat-guides",
    author: "Intellix Team",
    status: "PUBLISHED",
    version: "1.0",
    updatedAt: "2026-01-15T00:00:00.000Z",
    content: [
      "# Prompt Engineering",
      "",
      "A good prompt is specific, structured, and describes both subject and style.",
      "",
      "## Structure",
      "",
      "1. **Subject** - what is in the image",
      "2. **Environment** - where it happens",
      "3. **Lighting / mood** - atmosphere",
      "4. **Style** - photographic, anime, 3D render...",
      "",
      "## Examples",
      "",
      "Weak:",
      "> a cat",
      "",
      "Strong:",
      "> a fluffy white cat sitting on a rain-soaked Tokyo street at night, neon reflections, cinematic, shallow depth of field",
      "",
      "## Tips",
      "",
      "- Use the negative prompt to remove common artifacts",
      "- Stick to 1:1 for avatars, 16:9 for landscapes",
      "- Reuse your saved prompts to iterate faster",
    ].join("\n"),
  },
  {
    id: "doc-faq",
    slug: "faq",
    title: "FAQ",
    excerpt: "Common questions about Intellix.",
    categoryId: "cat-getting-started",
    author: "Intellix Team",
    status: "PUBLISHED",
    version: "1.0",
    updatedAt: "2026-01-15T00:00:00.000Z",
    content: [
      "# FAQ",
      "",
      "**What is my quota?**",
      "",
      "Your daily quota is shown in the sidebar. Each generation consumes credits from that quota.",
      "",
      "**Why did my generation fail?**",
      "",
      "Check the error on the generation card in your history. Common causes are a busy provider or an invalid prompt.",
      "",
      "**Where are my images stored?**",
      "",
      "Generated images are returned as base64 data URLs and kept in your generation history while you stay within the provider window.",
      "",
      "**Can I export images?**",
      "",
      "Yes - every image card has a download button.",
    ].join("\n"),
  },
];
